// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetBoutique.Api.Context;

#nullable disable

namespace PetBoutique.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetBoutique.Api.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fas fa-bone",
                            Nome = "Rações"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fas fa-futbol",
                            Nome = "Brinquedos"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fas fa-tag",
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fas fa-bath",
                            Nome = "Higiene"
                        },
                        new
                        {
                            Id = 5,
                            IconCSS = "fas fa-bed",
                            Nome = "Caminhas"
                        });
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Ração premium sabor frango e carne para cães adultos de médio e grande porte.",
                            ImagemUrl = "/Imagens/Racoes/golden15kg.png",
                            Nome = "Ração Golden Special Cães Adultos 15kg",
                            Preco = 135.50m,
                            Quantidade = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Alimento Super Premium para cães adultos que vivem dentro de casa.",
                            ImagemUrl = "/Imagens/Racoes/premier12kg.png",
                            Nome = "Ração Premier Ambientes Internos 12kg",
                            Preco = 210.90m,
                            Quantidade = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descricao = "Nutrição específica para cães da raça Shih Tzu.",
                            ImagemUrl = "/Imagens/Racoes/royalshih.png",
                            Nome = "Ração Royal Canin Shih Tzu 2.5kg",
                            Preco = 145.00m,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descricao = "Ração sabor carne para cães adultos.",
                            ImagemUrl = "/Imagens/Racoes/pedigree10kg.png",
                            Nome = "Ração Pedigree Nutrição Essencial 10kg",
                            Preco = 89.90m,
                            Quantidade = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descricao = "Petisco crocante para cães de todos os portes.",
                            ImagemUrl = "/Imagens/Racoes/biscrok.png",
                            Nome = "Biscoito Pedigree Biscrok 500g",
                            Preco = 15.50m,
                            Quantidade = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Descricao = "Bolinha super resistente para cães com mordida forte.",
                            ImagemUrl = "/Imagens/Brinquedos/bolinhamacica.png",
                            Nome = "Bolinha de Borracha Maciça",
                            Preco = 25.00m,
                            Quantidade = 40
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Descricao = "Corda resistente, ajuda na limpeza dos dentes enquanto o cão brinca.",
                            ImagemUrl = "/Imagens/Brinquedos/cordano.png",
                            Nome = "Corda com Nó para Morder",
                            Preco = 18.90m,
                            Quantidade = 55
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Descricao = "Bolinha com textura e cores de bola de vôlei para diversão em quadra ou no parque.",
                            ImagemUrl = "/Imagens/Brinquedos/bolapets.png",
                            Nome = "Bolinha estilo Vôlei Penalty para Pets",
                            Preco = 22.50m,
                            Quantidade = 30
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Descricao = "Frisbee de silicone que não machuca a boca do seu pet.",
                            ImagemUrl = "/Imagens/Brinquedos/frisbee.png",
                            Nome = "Frisbee Flexível",
                            Preco = 35.00m,
                            Quantidade = 25
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Descricao = "Brinquedo de pelúcia macio que emite som ao ser apertado.",
                            ImagemUrl = "/Imagens/Brinquedos/pelucia.png",
                            Nome = "Pelúcia com Apito",
                            Preco = 28.90m,
                            Quantidade = 45
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            Descricao = "Proporciona passeios mais tranquilos sem machucar o pescoço do animal.",
                            ImagemUrl = "/Imagens/Acessorios/peitoral.png",
                            Nome = "Coleira Peitoral Antipuxão",
                            Preco = 75.00m,
                            Quantidade = 35
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 3,
                            Descricao = "Liberdade com segurança durante os passeios.",
                            ImagemUrl = "/Imagens/Acessorios/guiaretratil.png",
                            Nome = "Guia Retrátil 5 metros",
                            Preco = 55.90m,
                            Quantidade = 40
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 3,
                            Descricao = "Comedouro durável e fácil de limpar.",
                            ImagemUrl = "/Imagens/Acessorios/comedouroinox.png",
                            Nome = "Comedouro de Inox Antiderrapante",
                            Preco = 32.00m,
                            Quantidade = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 3,
                            Descricao = "Água corrente e filtrada o dia todo para o seu pet.",
                            ImagemUrl = "/Imagens/Acessorios/fonteagua.png",
                            Nome = "Bebedouro Fonte Automática",
                            Preco = 140.00m,
                            Quantidade = 15
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 3,
                            Descricao = "Pingente de osso para gravação de nome e telefone.",
                            ImagemUrl = "/Imagens/Acessorios/plaquinha.png",
                            Nome = "Plaquinha de Identificação Personalizável",
                            Preco = 12.50m,
                            Quantidade = 100
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Descricao = "Tapetes com atrativo canino e fitas adesivas para fixação.",
                            ImagemUrl = "/Imagens/Higiene/tapete.png",
                            Nome = "Tapete Higiênico Super Absorvente (30 un)",
                            Preco = 65.00m,
                            Quantidade = 80
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 4,
                            Descricao = "Shampoo suave que realça a cor dos pelos.",
                            ImagemUrl = "/Imagens/Higiene/shampoo.png",
                            Nome = "Shampoo Neutro Pelos Claros",
                            Preco = 26.90m,
                            Quantidade = 50
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 4,
                            Descricao = "Remove pelos mortos e evita a formação de nós.",
                            ImagemUrl = "/Imagens/Higiene/rasqueadeira.png",
                            Nome = "Escova Rasqueadeira",
                            Preco = 30.00m,
                            Quantidade = 40
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 5,
                            Descricao = "Cama super macia com bordas elevadas para maior conforto.",
                            ImagemUrl = "/Imagens/Caminhas/camapremium.png",
                            Nome = "Cama Almofadada Premium",
                            Preco = 189.90m,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 5,
                            Descricao = "Ideal para cães pequenos que gostam de se esconder para dormir.",
                            ImagemUrl = "/Imagens/Caminhas/iglu.png",
                            Nome = "Cama Iglu Conforto",
                            Preco = 120.00m,
                            Quantidade = 15
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 5,
                            Descricao = "Colchonete prático, fácil de limpar e transportar.",
                            ImagemUrl = "/Imagens/Caminhas/colchonete.png",
                            Nome = "Colchonete Impermeável",
                            Preco = 85.00m,
                            Quantidade = 30
                        });
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeUsuario = "Gabryel"
                        },
                        new
                        {
                            Id = 2,
                            NomeUsuario = "Guilherme"
                        },
                        new
                        {
                            Id = 3,
                            NomeUsuario = "Breno"
                        },
                        new
                        {
                            Id = 4,
                            NomeUsuario = "Macoratti"
                        });
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Carrinho", b =>
                {
                    b.HasOne("PetBoutique.Api.Entities.Usuario", null)
                        .WithOne("Carrinho")
                        .HasForeignKey("PetBoutique.Api.Entities.Carrinho", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("PetBoutique.Api.Entities.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBoutique.Api.Entities.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Produto", b =>
                {
                    b.HasOne("PetBoutique.Api.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Produto", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PetBoutique.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Carrinho");
                });
#pragma warning restore 612, 618
        }
    }
}
